server: "hub-cloud.browserstack.com"
user: ""
key: ""

common_caps:
  "build": "rspec-browserstack"
  "browserstack.local": true
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
