server: "hub-cloud.browserstack.com"
user: ""
key: ""

common_caps:
  "build": "rspec-browserstack"
  "browserstack.debug": true
  "browserstack.local": true
  "browserstack.localIdentifier": 'randomstring'


browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"

